# Start from the official devcontainers Rust image (includes Rust, Cargo, etc.).
FROM mcr.microsoft.com/devcontainers/rust:1

# [Optional] Install additional packages here, for example:
# RUN apt-get update && apt-get install -y <some-packages>
